# add travi yml file and and
language: java
dist: trusty
sudo: required

before_install:
- sudo apt-get install software-properties-common -y
- sudo apt-add-repository ppa:brightbox/ruby-ng -y
- sudo apt-get update
- sudo apt-get install build-essential ruby2.2 ruby2.2-dev zlib1g-dev liblzma-dev -y
- sudo gem install bundler
- sudo gem install deb-s3

script:
- ./gradlew clean packDeb
#- deb-s3 upload --bucket test-spinnaker-delete --access-key-id $ARTIFACTS_KEY --secret-access-key $ARTIFACTS_SECRET --arch amd64 --codename trusty --preserve-versions true build/distributions/*.deb

addons:
  artifacts: true
    s3_region: "us-east-2" # defaults to "us-east-1"
